services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: