version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis

  back:
    image: golang
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    ports:
      - 8080:8080
    command: sh -c "go mod download && go install github.com/canthefason/go-watcher/cmd/watcher && /go/bin/watcher"