// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  footer: string;
  head: string;
  logo: string;
}
declare const cssExports: CssExports;
export default cssExports;
