version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1zad2bulki
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432